on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - toolchain: stable
          - toolchain: nightly
          - toolchain: nightly
            features: unstable
    steps:
      - uses: actions/checkout@v4
      - run: rustup override  set ${{ matrix.toolchain }}
      - run: rustup component add clippy --toolchain ${{ matrix.toolchain }}
      - run: cargo doc    --features=${{ matrix.features }}
      - run: cargo test   --features=${{ matrix.features }}
      - run: cargo clippy --features=${{ matrix.features }} -- -D warnings
